// Code generated by protoc-gen-go.
// source: tsp.proto
// DO NOT EDIT!

/*
Package tsp is a generated protocol buffer package.

It is generated from these files:
	tsp.proto

It has these top-level messages:
	Empty
	PublishAppRequest
	PublishAppResponse
	ListAppsResponse
	ListAppObject
	GetAppRequest
	GetAppResponse
	RegisterClusterRequest
	RegisterClusterResponse
	CreateUserRequest
	User
*/
package tsp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PublishAppRequest struct {
	AppName     string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Publisher   string `protobuf:"bytes,3,opt,name=publisher" json:"publisher,omitempty"`
	Version     string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	AppData     []byte `protobuf:"bytes,5,opt,name=app_data,json=appData,proto3" json:"app_data,omitempty"`
}

func (m *PublishAppRequest) Reset()                    { *m = PublishAppRequest{} }
func (m *PublishAppRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishAppRequest) ProtoMessage()               {}
func (*PublishAppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PublishAppResponse struct {
	AppId     string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppName   string `protobuf:"bytes,2,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Published string `protobuf:"bytes,3,opt,name=published" json:"published,omitempty"`
}

func (m *PublishAppResponse) Reset()                    { *m = PublishAppResponse{} }
func (m *PublishAppResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishAppResponse) ProtoMessage()               {}
func (*PublishAppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListAppsResponse struct {
	List []*ListAppObject `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListAppsResponse) Reset()                    { *m = ListAppsResponse{} }
func (m *ListAppsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAppsResponse) ProtoMessage()               {}
func (*ListAppsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListAppsResponse) GetList() []*ListAppObject {
	if m != nil {
		return m.List
	}
	return nil
}

type ListAppObject struct {
	AppId       string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppName     string `protobuf:"bytes,2,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Publisher   string `protobuf:"bytes,4,opt,name=publisher" json:"publisher,omitempty"`
	Version     string `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
}

func (m *ListAppObject) Reset()                    { *m = ListAppObject{} }
func (m *ListAppObject) String() string            { return proto.CompactTextString(m) }
func (*ListAppObject) ProtoMessage()               {}
func (*ListAppObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetAppRequest struct {
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
}

func (m *GetAppRequest) Reset()                    { *m = GetAppRequest{} }
func (m *GetAppRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAppRequest) ProtoMessage()               {}
func (*GetAppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetAppResponse struct {
	AppData []byte `protobuf:"bytes,1,opt,name=app_data,json=appData,proto3" json:"app_data,omitempty"`
}

func (m *GetAppResponse) Reset()                    { *m = GetAppResponse{} }
func (m *GetAppResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAppResponse) ProtoMessage()               {}
func (*GetAppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RegisterClusterRequest struct {
	UserToken string `protobuf:"bytes,1,opt,name=UserToken" json:"UserToken,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Subdomain string `protobuf:"bytes,3,opt,name=Subdomain" json:"Subdomain,omitempty"`
}

func (m *RegisterClusterRequest) Reset()                    { *m = RegisterClusterRequest{} }
func (m *RegisterClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterClusterRequest) ProtoMessage()               {}
func (*RegisterClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RegisterClusterResponse struct {
	OtpToken string `protobuf:"bytes,1,opt,name=otp_token,json=otpToken" json:"otp_token,omitempty"`
}

func (m *RegisterClusterResponse) Reset()                    { *m = RegisterClusterResponse{} }
func (m *RegisterClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterClusterResponse) ProtoMessage()               {}
func (*RegisterClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CreateUserRequest struct {
	Username    string            `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	FirstName   string            `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName    string            `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email       string            `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	MobilePhone string            `protobuf:"bytes,5,opt,name=mobile_phone,json=mobilePhone" json:"mobile_phone,omitempty"`
	Password    string            `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
	Group       string            `protobuf:"bytes,7,opt,name=group" json:"group,omitempty"`
	Fields      map[string]string `protobuf:"bytes,8,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateUserRequest) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type User struct {
	UserId      int32             `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Username    string            `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName   string            `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName    string            `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email       string            `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	MobilePhone string            `protobuf:"bytes,6,opt,name=mobile_phone,json=mobilePhone" json:"mobile_phone,omitempty"`
	Group       string            `protobuf:"bytes,7,opt,name=group" json:"group,omitempty"`
	Fields      map[string]string `protobuf:"bytes,8,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *User) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "tsp.Empty")
	proto.RegisterType((*PublishAppRequest)(nil), "tsp.PublishAppRequest")
	proto.RegisterType((*PublishAppResponse)(nil), "tsp.PublishAppResponse")
	proto.RegisterType((*ListAppsResponse)(nil), "tsp.ListAppsResponse")
	proto.RegisterType((*ListAppObject)(nil), "tsp.ListAppObject")
	proto.RegisterType((*GetAppRequest)(nil), "tsp.GetAppRequest")
	proto.RegisterType((*GetAppResponse)(nil), "tsp.GetAppResponse")
	proto.RegisterType((*RegisterClusterRequest)(nil), "tsp.RegisterClusterRequest")
	proto.RegisterType((*RegisterClusterResponse)(nil), "tsp.RegisterClusterResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "tsp.CreateUserRequest")
	proto.RegisterType((*User)(nil), "tsp.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tsp service

type TspClient interface {
	RegisterCluster(ctx context.Context, in *RegisterClusterRequest, opts ...grpc.CallOption) (*RegisterClusterResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	PublishApp(ctx context.Context, in *PublishAppRequest, opts ...grpc.CallOption) (*PublishAppResponse, error)
	ListApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAppsResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error)
}

type tspClient struct {
	cc *grpc.ClientConn
}

func NewTspClient(cc *grpc.ClientConn) TspClient {
	return &tspClient{cc}
}

func (c *tspClient) RegisterCluster(ctx context.Context, in *RegisterClusterRequest, opts ...grpc.CallOption) (*RegisterClusterResponse, error) {
	out := new(RegisterClusterResponse)
	err := grpc.Invoke(ctx, "/tsp.Tsp/RegisterCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tspClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/tsp.Tsp/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tspClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/tsp.Tsp/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tspClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/tsp.Tsp/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tspClient) PublishApp(ctx context.Context, in *PublishAppRequest, opts ...grpc.CallOption) (*PublishAppResponse, error) {
	out := new(PublishAppResponse)
	err := grpc.Invoke(ctx, "/tsp.Tsp/PublishApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tspClient) ListApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	out := new(ListAppsResponse)
	err := grpc.Invoke(ctx, "/tsp.Tsp/ListApps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tspClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error) {
	out := new(GetAppResponse)
	err := grpc.Invoke(ctx, "/tsp.Tsp/GetApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tsp service

type TspServer interface {
	RegisterCluster(context.Context, *RegisterClusterRequest) (*RegisterClusterResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	UpdateUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *User) (*User, error)
	PublishApp(context.Context, *PublishAppRequest) (*PublishAppResponse, error)
	ListApps(context.Context, *Empty) (*ListAppsResponse, error)
	GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error)
}

func RegisterTspServer(s *grpc.Server, srv TspServer) {
	s.RegisterService(&_Tsp_serviceDesc, srv)
}

func _Tsp_RegisterCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).RegisterCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/RegisterCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).RegisterCluster(ctx, req.(*RegisterClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsp_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsp_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsp_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsp_PublishApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).PublishApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/PublishApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).PublishApp(ctx, req.(*PublishAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsp_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/ListApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).ListApps(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsp_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TspServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsp.Tsp/GetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TspServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tsp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tsp.Tsp",
	HandlerType: (*TspServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCluster",
			Handler:    _Tsp_RegisterCluster_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Tsp_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Tsp_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Tsp_DeleteUser_Handler,
		},
		{
			MethodName: "PublishApp",
			Handler:    _Tsp_PublishApp_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _Tsp_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _Tsp_GetApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsp.proto",
}

func init() { proto.RegisterFile("tsp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0xc6, 0x76, 0xec, 0xd8, 0x27, 0xb0, 0x0b, 0xc3, 0x02, 0x5e, 0x93, 0x95, 0xb2, 0x56, 0x85,
	0x90, 0xaa, 0xa6, 0x2a, 0x48, 0x55, 0xcb, 0x4d, 0xc5, 0x5f, 0x2b, 0xa4, 0x8a, 0x46, 0x29, 0x5c,
	0xa3, 0x09, 0x1e, 0xc0, 0xc5, 0x8e, 0xa7, 0x33, 0x63, 0x10, 0xcf, 0xd2, 0xcb, 0xbe, 0x40, 0x5f,
	0xa4, 0x4f, 0xd4, 0x9b, 0x6a, 0xc6, 0x9e, 0xc4, 0x4e, 0xd2, 0x20, 0x55, 0xbd, 0x82, 0xf3, 0x9d,
	0xbf, 0x6f, 0xbe, 0x73, 0x72, 0x0c, 0x9e, 0xe0, 0xb4, 0x4b, 0x59, 0x26, 0x32, 0x64, 0x09, 0x4e,
	0xc3, 0x26, 0xd8, 0xc7, 0x29, 0x15, 0x0f, 0xe1, 0x57, 0x03, 0x56, 0x7a, 0xf9, 0x20, 0x89, 0xf9,
	0xcd, 0x3e, 0xa5, 0x7d, 0xf2, 0x39, 0x27, 0x5c, 0xa0, 0x7f, 0xc1, 0xc5, 0x94, 0x5e, 0x0c, 0x71,
	0x4a, 0x7c, 0xa3, 0x63, 0x6c, 0x7b, 0xfd, 0x26, 0xa6, 0xf4, 0x14, 0xa7, 0x04, 0x75, 0xa0, 0x15,
	0x11, 0x7e, 0xc9, 0x62, 0x2a, 0xe2, 0x6c, 0xe8, 0x9b, 0xca, 0x5b, 0x85, 0x50, 0x1b, 0x3c, 0x5a,
	0x54, 0x24, 0xcc, 0xb7, 0x94, 0x7f, 0x0c, 0x20, 0x1f, 0x9a, 0x77, 0x84, 0x71, 0x99, 0xdb, 0x28,
	0x2a, 0x97, 0xa6, 0x6e, 0x1a, 0x61, 0x81, 0x7d, 0xbb, 0x63, 0x6c, 0x2f, 0xaa, 0xa6, 0x47, 0x58,
	0xe0, 0x30, 0x02, 0x54, 0x25, 0xc9, 0x69, 0x36, 0xe4, 0x04, 0xad, 0x81, 0x23, 0x13, 0xe2, 0xa8,
	0xe4, 0x68, 0x63, 0x4a, 0x4f, 0xa2, 0x1a, 0x79, 0xb3, 0x4e, 0xbe, 0x42, 0x2d, 0x9a, 0xa4, 0x16,
	0x85, 0x7b, 0xb0, 0xfc, 0x3e, 0xe6, 0x62, 0x9f, 0x52, 0x3e, 0xea, 0xb1, 0x05, 0x8d, 0x24, 0xe6,
	0xc2, 0x37, 0x3a, 0xd6, 0x76, 0x6b, 0x07, 0x75, 0xa5, 0x8e, 0x65, 0xd0, 0x87, 0xc1, 0x27, 0x72,
	0x29, 0xfa, 0xca, 0x1f, 0x7e, 0x31, 0x60, 0xa9, 0x86, 0xff, 0x06, 0xbb, 0x09, 0x69, 0xad, 0x47,
	0xa4, 0x6d, 0xcc, 0x91, 0xd6, 0xae, 0x49, 0x1b, 0x6e, 0xc1, 0xd2, 0x3b, 0x22, 0x2a, 0x03, 0x9e,
	0x4d, 0x2e, 0x7c, 0x0a, 0x7f, 0xe9, 0xb8, 0xf2, 0xfd, 0xd5, 0xa1, 0x18, 0xf5, 0xa1, 0x50, 0x58,
	0xef, 0x93, 0xeb, 0x98, 0x0b, 0xc2, 0x0e, 0x93, 0x5c, 0xfe, 0xd1, 0xd5, 0xdb, 0xe0, 0x9d, 0x73,
	0xc2, 0xce, 0xb2, 0x5b, 0x32, 0x2c, 0x1b, 0x8c, 0x01, 0x14, 0x80, 0xdb, 0xc3, 0x9c, 0xdf, 0x67,
	0x2c, 0x2a, 0x15, 0x18, 0xd9, 0x32, 0xf3, 0x63, 0x3e, 0x88, 0xb2, 0x14, 0xc7, 0x5a, 0x80, 0x31,
	0x10, 0xbe, 0x84, 0x8d, 0xa9, 0x8e, 0x25, 0xcf, 0x4d, 0xf0, 0x32, 0x41, 0x2f, 0x44, 0xa5, 0xa5,
	0x9b, 0x09, 0xaa, 0x3a, 0x86, 0xdf, 0x4d, 0x58, 0x39, 0x64, 0x04, 0x0b, 0x22, 0x59, 0x68, 0x96,
	0x01, 0xb8, 0x39, 0x27, 0xac, 0xb2, 0xe4, 0x23, 0x1b, 0xfd, 0x07, 0x70, 0x15, 0x33, 0x2e, 0xaa,
	0x73, 0xf2, 0x14, 0xa2, 0x26, 0xb5, 0x09, 0x5e, 0x82, 0xb5, 0xb7, 0xa0, 0xe9, 0x4a, 0x40, 0x39,
	0xff, 0x01, 0x9b, 0xa4, 0x38, 0x4e, 0xca, 0x01, 0x15, 0x06, 0xfa, 0x1f, 0x16, 0xd3, 0x6c, 0x10,
	0x27, 0xe4, 0x82, 0xde, 0x64, 0x43, 0x52, 0x4e, 0xa8, 0x55, 0x60, 0x3d, 0x09, 0x49, 0x42, 0x54,
	0x0b, 0xe3, 0x14, 0x45, 0xb5, 0x2d, 0x8b, 0x5e, 0xb3, 0x2c, 0xa7, 0x7e, 0xb3, 0x28, 0xaa, 0x0c,
	0xb4, 0x07, 0xce, 0x55, 0x4c, 0x92, 0x88, 0xfb, 0xae, 0xda, 0xcf, 0x50, 0xed, 0xe7, 0xd4, 0x53,
	0xbb, 0x6f, 0x55, 0xd0, 0xf1, 0x50, 0xb0, 0x87, 0x7e, 0x99, 0x11, 0xbc, 0x86, 0x56, 0x05, 0x46,
	0xcb, 0x60, 0xdd, 0x92, 0x87, 0x52, 0x08, 0xf9, 0xaf, 0x6c, 0x79, 0x87, 0x93, 0x5c, 0x3f, 0xbf,
	0x30, 0xf6, 0xcc, 0x57, 0x46, 0xf8, 0xcd, 0x84, 0x86, 0x2c, 0x8f, 0x36, 0xa0, 0x29, 0x25, 0xd3,
	0x7b, 0x64, 0xf7, 0x1d, 0x69, 0x9e, 0x44, 0x35, 0x6d, 0xcd, 0xb9, 0xda, 0x5a, 0x73, 0xb5, 0x6d,
	0xfc, 0x4a, 0x5b, 0x7b, 0x9e, 0xb6, 0xce, 0xb4, 0xb6, 0xb3, 0xf5, 0x7b, 0x36, 0xa1, 0xdf, 0x9a,
	0xd2, 0x4f, 0x3e, 0xed, 0x0f, 0x4b, 0xb6, 0xf3, 0xc3, 0x04, 0xeb, 0x8c, 0x53, 0x74, 0x0a, 0x7f,
	0x4f, 0xac, 0x30, 0xda, 0x54, 0x4d, 0x67, 0xff, 0x94, 0x82, 0xf6, 0x6c, 0x67, 0xb1, 0xf5, 0xe1,
	0x02, 0x7a, 0x01, 0x30, 0x1e, 0x37, 0x5a, 0x9f, 0x3d, 0xff, 0xc0, 0x1b, 0xbd, 0x2b, 0x5c, 0x40,
	0x4f, 0x00, 0xce, 0x69, 0xa4, 0x53, 0xc6, 0xae, 0xa9, 0xa8, 0x23, 0x92, 0x90, 0x47, 0xa2, 0xde,
	0x00, 0x8c, 0x0f, 0x73, 0xd9, 0x7e, 0xea, 0x73, 0x12, 0x6c, 0x4c, 0xe1, 0x23, 0xfe, 0xcf, 0xc1,
	0xd5, 0x37, 0x17, 0x81, 0x0a, 0x53, 0xdf, 0xa5, 0x60, 0xad, 0x7a, 0x69, 0x79, 0x25, 0x61, 0x17,
	0x9c, 0xe2, 0x44, 0xa1, 0xe2, 0x18, 0xd7, 0xee, 0x5a, 0xb0, 0x5a, 0xc3, 0x74, 0xd2, 0x41, 0x1b,
	0x56, 0x53, 0xc2, 0x6f, 0xee, 0x71, 0x72, 0x4b, 0x58, 0xf7, 0x9a, 0xd1, 0x4b, 0x19, 0x77, 0x20,
	0x27, 0xd2, 0x33, 0x06, 0x8e, 0xfa, 0x30, 0xee, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x4f,
	0xc0, 0xf3, 0x25, 0x07, 0x00, 0x00,
}
